// Deterministic assembly only. No Jira calls or downloads.
def root = new File(args ? args[0] : '.').canonicalFile
def destination = new File(root, 'dist/plan-permission-cover.groovy')
destination.parentFile.mkdirs()
def normalise = { String text -> text.replace('\r\n', '\n').trim() + '\n' }
def content = '// Generated by tools/build.groovy. Do not edit this copy.\n' +
    '// New read-only example; not the historical production removal script.\n\n' +
    normalise(new File(root, 'scripts/console-entrypoint.groovy').getText('UTF-8')) + '\n' +
    normalise(new File(root, 'src/PermissionCover.groovy').getText('UTF-8'))
destination.setText(content, 'UTF-8')
println 'Built dist/plan-permission-cover.groovy'
